#!/bin/sh -e
sed -i -e "s/%PKG_CONFIG%/pkg-config/" builds/unix/freetype-config.in
./configure \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --enable-freetype-config \
    --with-harfbuzz=no
make
make DESTDIR="$1" install
