#!/bin/sh -e
meson setup build \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --libdir=lib \
    --buildtype=release \
    -Denable_gtk_doc=true \
    -Dwith_vapi=true \
    -Dwith_introspection=true
ninja -C build
DESTDIR="$1" ninja -C build install
