#!/bin/sh -e
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLIBDEFLATE_USE_SHARED_LIB=ON
ninja -C build
DESTDIR="$1" ninja -C build install
