#!/bin/sh -e
./configure \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --enable-transparent \
    --localstatedir="$CHY_ROOT/var" \
    tinyproxy_cv_regex_broken=no
make
make DESTDIR="$1" install
sed -i "$1$CHY_ROOT/etc/tinyproxy/tinyproxy.conf" -e 's/^User .*/User _tinyproxy/' -e 's/^Group .*/Group _tinyproxy/'
