#!/bin/sh -e
export CFLAGS="${CFLAGS:+$CFLAGS }-D_FILE_OFFSET_BITS=64 -D_TIME_BITS=64"
./configure \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    gl_cv_func_gettimeofday_clobber=no \
    gl_cv_func_tzset_clobber=no
make
make DESTDIR="$1" install
