#!/bin/sh -e
./configure \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc"
make
install -Dm755 dtach "$1$CHY_ROOT/usr/bin/dtach"
install -Dm644 dtach.1 "$1$CHY_ROOT/usr/share/man/man1/dtach.1"
