#!/bin/sh -e
./configure \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --disable-executable
make
make DESTDIR="$1" install
rm -rf "$1$CHY_ROOT/usr/bin/rw"
rm -rf "$1$CHY_ROOT/usr/share/doc/rw"
