#!/bin/sh -e
meson setup build \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --libdir=lib \
    --buildtype=release \
    -Dintrospection=enabled \
    -Ddocumentation=enabled
ninja -C build
DESTDIR="$1" ninja -C build install
rm -r "$1$CHY_ROOT/usr/share/installed-tests"
rm -r "$1$CHY_ROOT/usr/libexec/installed-tests"
