#!/bin/sh -e
mkdir -p "$1$CHY_ROOT/usr/share/fonts/TTF"
install -m644 ttf/*.ttf "$1$CHY_ROOT/usr/share/fonts/TTF"
mkdir -p "$1$CHY_ROOT/etc/fonts/conf.avail"
install -m644 fontconfig/*.conf "$1$CHY_ROOT/etc/fonts/conf.avail"
