#!/bin/sh -e
make
install -Dm755 growisofs "$1$CHY_ROOT/usr/bin/growisofs"
install -Dm755 dvd+rw-booktype "$1$CHY_ROOT/usr/bin/dvd+rw-booktype"
install -Dm755 dvd+rw-format "$1$CHY_ROOT/usr/bin/dvd+rw-format"
install -Dm755 dvd+rw-mediainfo "$1$CHY_ROOT/usr/bin/dvd+rw-mediainfo"
install -Dm755 dvd-ram-control "$1$CHY_ROOT/usr/bin/dvd-ram-control"
install -Dm644 growisofs.1 "$1$CHY_ROOT/usr/share/man/man1/growisofs.1"
