#!/bin/sh -e
meson setup build \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --libdir=lib \
    --buildtype=release \
    -Dinstalled_tests=false \
    -Dintrospection=enabled \
    -Dsse2=true \
    -Darm_neon=false \
    -Dgcc_vector=true
ninja -C build
DESTDIR="$1" ninja -C build install
