#!/bin/sh -e
meson setup build \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --libdir=lib \
    --buildtype=release
ninja -C build
DESTDIR="$1" ninja -C build install
rm -r "$1$CHY_ROOT/usr/lib/cmake"
