#!/bin/sh -e
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLHTTP_BUILD_SHARED_LIBS=ON \
    -DLLHTTP_BUILD_STATIC_LIBS=ON
ninja -C build
DESTDIR="$1" ninja -C build install
