#!/bin/sh -e
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCLI11_BUILD_TESTS=OFF \
    -DCLI11_BUILD_EXAMPLES=OFF
ninja -C build
DESTDIR="$1" ninja -C build install
