#!/bin/sh -e
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_SKIP_RPATH=ON
ninja -C build
DESTDIR="$1" ninja -C build install
