#!/bin/sh -e
sed -i 's| -O0||g' config.mk
sed -i 's|^CPPFLAGS *=|override CPPFLAGS +=|g' config.mk
sed -i 's|^CFLAGS *=|override CFLAGS +=|g' config.mk
sed -i 's|^LDFLAGS *=|override LDFLAGS +=|g' config.mk
make \
    INCS=-I. \
    LIBS=-lX11
make PREFIX="$CHY_PREFIX" DESTDIR="$1" install
