#!/bin/sh -e
meson setup build \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --libdir=lib \
    --buildtype=release \
    -Dmbim_qmux=true \
    -Dqrtr=true \
    -Dintrospection=true \
    -Dman=false
ninja -C build
DESTDIR="$1" ninja -C build install
