#!/bin/sh -e
mkdir -p "$1$CHY_ROOT/usr/share/fonts/TTF"
mkdir -p "$1$CHY_ROOT/usr/share/fonts/OTF"
mkdir -p "$1$CHY_ROOT/etc/fonts/conf.avail"
install -m644 *.ttf "$1$CHY_ROOT/usr/share/fonts/TTF"
install -m644 *.otf "$1$CHY_ROOT/usr/share/fonts/OTF"
install -Dm644 culmus.conf "$1$CHY_ROOT/etc/fonts/conf.avail/61-culmus.conf/culmus.conf"
