#!/bin/sh -e
./configure \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --with-xinitdir="$CHY_ROOT/etc/X11/xinit"
make
make DESTDIR="$1" install
install -Dm644 xserverrc "$1$CHY_ROOT/etc/X11/xinit/xserverrc"
