#!/bin/sh -e
meson setup build \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --libdir=lib \
    --buildtype=release \
    -Dwith-docs=false \
    -Denable-gir=true
ninja -C build
DESTDIR="$1" ninja -C build install
