#!/bin/sh -e
export CFLAGS="${CFLAGS:+$CFLAGS }-D_LARGE_FILE_SOURCE=1 -D_FILE_OFFSET_BITS=64"
./configure \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc"
make
make DESTDIR="$1" install
