#!/bin/sh -e
meson setup build \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --libdir=lib \
    --buildtype=release \
    -Dxorg-rules-symlinks=true \
    -Dcompat-rules=true
ninja -C build
DESTDIR="$1" ninja -C build install
