#!/bin/sh -e
meson setup build \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --libdir=lib \
    --buildtype=release \
    -Ddistro_install=true \
    -Ddefault_library=shared
ninja -C build
DESTDIR="$1" ninja -C build install
