#!/bin/sh -e
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DTTY_GID_SUPPORT_EXITCODE=1 \
    -DTTY_GID_SUPPORT_EXITCODE__TRYRUN_OUTPUT=
ninja -C build
DESTDIR="$1" ninja -C build install
