#!/bin/sh -e
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON
ninja -C build
DESTDIR="$1" ninja -C build install
install -Dm644 id3tag.pc "$1$CHY_ROOT/usr/lib/pkgconfig/id3tag.pc"
