#!/bin/sh -e
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_ZLIB_COMPRESSION=ON \
    -DRUN_DOCKER_TESTS=OFF
ninja -C build
DESTDIR="$1" ninja -C build install
