#!/bin/sh -e
meson setup build \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --libdir=lib \
    --buildtype=release \
    -Dgtkdoc=false \
    -Dtests=false \
    -Dstemmer=false \
    -Dintrospection=true
ninja -C build
DESTDIR="$1" ninja -C build install
rm -rf "$1$CHY_ROOT/usr/share/installed-tests"
