#!/bin/sh -e
meson setup build \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --libdir=lib \
    --buildtype=release \
    -Ddocumentation=false \
    -Db_ndebug=false \
    -Dtests=false
ninja -C build
DESTDIR="$1" ninja -C build install
