#!/bin/sh -e
export CXXFLAGS="${CXXFLAGS:+$CXXFLAGS }-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON
ninja -C build
DESTDIR="$1" ninja -C build install
