#!/bin/sh -e
./configure \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --with-ttfdir="$CHY_ROOT/usr/share/fonts/TTF" \
    --with-otfdir="$CHY_ROOT/usr/share/fonts/OTF" \
    --enable-ttf
make
make DESTDIR="$1" install
