#!/bin/sh -e
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DEXIV2_BUILD_SAMPLES=OFF \
    -DEXIV2_ENABLE_BMFF=ON
ninja -C build
DESTDIR="$1" ninja -C build install
