#!/bin/sh -e
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=true \
    -DBUILD_TZ_LIB=true \
    -DUSE_SYSTEM_TZ_DB=true \
    -DENABLE_DATE_TESTING=false
ninja -C build
DESTDIR="$1" ninja -C build install
