#!/bin/sh -e
./configure \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc"
make
make DESTDIR="$1" install
rm "$1$CHY_ROOT/usr/share/the_silver_searcher/completions/ag.bashcomp.sh"
install -Dm644 ag.bashcomp.sh "$1$CHY_ROOT/usr/share/bash-completion/completions/ag"
install -Dm644 _the_silver_searcher "$1$CHY_ROOT/usr/share/zsh/site-functions/_the_silver_searcher"
