#!/bin/sh -e
./configure \
    --prefix="$CHY_PREFIX" \
    --sysconfdir="$CHY_ROOT/etc" \
    --with-readline \
    es_cv_abused_getenv=no
make
make DESTDIR="$1" install
install -Dm755 esdebug "$1$CHY_ROOT/usr/bin/esdebug"
