#!/bin/sh -e
cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX="$CHY_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release
ninja -C build
DESTDIR="$1" ninja -C build install
install -Dm644 rtl-sdr.rules "$1$CHY_ROOT/usr/lib/udev/rules.d/53-rtl-sdr.rules"
